#!/usr/bin/env python3
"""Generate the shared canonical face topology for @beautymade/face-engine.

Reads MediaPipe's canonical face model (468 vertices / 898 triangles, Apache-2.0)
from the API service and writes a TypeScript module so the mobile app and the
reconstruction service share one topology (same vertex order, UVs, triangles).

Usage:  python3 scripts/gen_canonical_topology.py
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OBJ_PATH = ROOT / "services/api/app/reconstruction/data/canonical_face_model.obj"
OUT_PATH = ROOT / "packages/face-engine/src/topology/canonical.generated.ts"


def load_obj(path: Path):
    positions: list[list[float]] = []
    uvs_raw: list[list[float]] = []
    faces: list[list[tuple[int, int]]] = []
    for line in path.read_text().splitlines():
        parts = line.split()
        if not parts:
            continue
        if parts[0] == "v":
            positions.append([float(x) for x in parts[1:4]])
        elif parts[0] == "vt":
            uvs_raw.append([float(x) for x in parts[1:3]])
        elif parts[0] == "f":
            faces.append([tuple(int(i) - 1 for i in p.split("/")[:2]) for p in parts[1:4]])  # type: ignore[misc]

    # The OBJ indexes UVs separately, but every vertex maps to exactly one UV.
    uv_of_vertex: dict[int, int] = {}
    for face in faces:
        for v, t in face:
            if uv_of_vertex.setdefault(v, t) != t:
                raise ValueError(f"vertex {v} has multiple UVs")
    uvs = [uvs_raw[uv_of_vertex[v]] for v in range(len(positions))]
    triangles = [[v for v, _ in face] for face in faces]
    return positions, uvs, triangles


def orient_outward(positions, triangles):
    """Make triangle winding counter-clockwise when seen from the front (+z)."""
    total = 0.0
    for a, b, c in triangles:
        ax, ay, _ = positions[a]
        bx, by, _ = positions[b]
        cx, cy, _ = positions[c]
        total += (bx - ax) * (cy - ay) - (by - ay) * (cx - ax)
    if total < 0:
        return [[a, c, b] for a, b, c in triangles]
    return triangles


def boundary_loop(triangles):
    edges = Counter()
    for a, b, c in triangles:
        for e in ((a, b), (b, c), (c, a)):
            edges[tuple(sorted(e))] += 1
    boundary = [e for e, n in edges.items() if n == 1]
    adj: dict[int, list[int]] = {}
    for a, b in boundary:
        adj.setdefault(a, []).append(b)
        adj.setdefault(b, []).append(a)
    # Start at the forehead top (landmark 10) and walk towards the subject's left.
    start = 10
    loop = [start]
    prev, cur = None, start
    while True:
        nxt = [n for n in adj[cur] if n != prev]
        nxt_v = nxt[0] if prev is not None else max(adj[cur])
        if nxt_v == start:
            break
        loop.append(nxt_v)
        prev, cur = cur, nxt_v
    if len(loop) != len(boundary):
        raise ValueError("face boundary is not a single loop")
    return loop


def fmt(value: float, digits: int) -> str:
    text = f"{value:.{digits}f}".rstrip("0").rstrip(".")
    return "0" if text in ("", "-0") else text


def main() -> None:
    positions, uvs, triangles = load_obj(OBJ_PATH)
    triangles = orient_outward(positions, triangles)
    oval = boundary_loop(triangles)
    flat_pos = [c for p in positions for c in p]
    flat_uv = [c for p in uvs for c in p]
    flat_tri = [i for t in triangles for i in t]

    def chunked(items: list[str], per_line: int) -> str:
        lines = [",".join(items[i : i + per_line]) for i in range(0, len(items), per_line)]
        return ",\n  ".join(lines)

    pos_items = [fmt(v, 5) for v in flat_pos]
    uv_items = [fmt(v, 6) for v in flat_uv]
    tri_items = [str(i) for i in flat_tri]

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(
        f"""// AUTO-GENERATED by scripts/gen_canonical_topology.py. Do not edit by hand.
// Source: MediaPipe canonical face model (Apache License 2.0),
// https://github.com/google-ai-edge/mediapipe/tree/master/mediapipe/modules/face_geometry/data

/** Number of MediaPipe face mesh landmarks that form the base topology. */
export const CANONICAL_VERTEX_COUNT = {len(positions)};

/** Number of triangles in the base topology. */
export const CANONICAL_TRIANGLE_COUNT = {len(triangles)};

/**
 * Canonical (average, symmetric) face in centimetre-like units.
 * Frame: +x = viewer's right (subject's left), +y = up, +z = towards the viewer.
 */
export const CANONICAL_POSITIONS: readonly number[] = [
  {chunked(pos_items, 12)},
];

/** Canonical UV layout in [0, 1], v pointing up (OBJ convention). */
export const CANONICAL_UVS: readonly number[] = [
  {chunked(uv_items, 12)},
];

/** Triangles, counter-clockwise when seen from the front. */
export const CANONICAL_TRIANGLES: readonly number[] = [
  {chunked(tri_items, 24)},
];

/** Ordered boundary loop of the face mesh (the face oval), starting at the forehead top. */
export const FACE_OVAL: readonly number[] = [{", ".join(str(i) for i in oval)}];
"""
    )
    print(f"wrote {OUT_PATH.relative_to(ROOT)}: {len(positions)} vertices, {len(triangles)} triangles, oval {len(oval)}")


if __name__ == "__main__":
    main()
