#!/usr/bin/env python3
"""
Generates the bundled demo face used by the app before a user has scanned (and in demo
mode). It is a sample portrait (an AI-generated face from the app's design sample, not a
real person) put through the same reconstruction as a real scan, so the demo has photo
textures, eye measurements and the eyeball atlas like a user's own face.

Usage (from services/api):  .venv/bin/python scripts/make_demo_face.py [photo] [out_dir]
"""

from __future__ import annotations

import base64
import json
import sys
from pathlib import Path

import cv2
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.reconstruction.pipeline import reconstruct  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
PHOTO = Path(__file__).parent / "data" / "demo_face.jpg"
DEFAULT_OUT = ROOT / "apps" / "mobile" / "assets" / "demo-face"
TEXTURES_TS = ROOT / "apps" / "mobile" / "src" / "three" / "demoFaceTextures.generated.ts"
# The sample's face is only ~120 px wide: enlarge it to phone-photo size before scanning.
UPSCALE = 4


def main() -> None:
    photo_path = Path(sys.argv[1]) if len(sys.argv) > 1 else PHOTO
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUT
    out.mkdir(parents=True, exist_ok=True)

    small = cv2.cvtColor(cv2.imread(str(photo_path)), cv2.COLOR_BGR2RGB)
    big = cv2.resize(small, None, fx=UPSCALE, fy=UPSCALE, interpolation=cv2.INTER_LANCZOS4)
    photo = cv2.addWeighted(big, 1.4, cv2.GaussianBlur(big, (0, 0), 2), -0.4, 0)  # gentle unsharp mask
    result = reconstruct({"front": photo})

    model = {key: result.model[key] for key in ("format", "version", "mesh", "atlasSize", "atlas", "skinTone")}
    model["eyes"] = result.model["eyes"]
    model["eyeTexture"] = result.model["eyeTexture"]
    if not (model["eyes"] and model["eyeTexture"] and result.eyes_jpg):
        raise SystemExit("the sample photo's eyes could not be measured; pick a clearer frontal photo")
    (out / "model.json").write_text(json.dumps(model, separators=(",", ":")))

    # Textures are embedded as data URLs, which load the same way on iOS, Android and web.
    def data_url(data: bytes, mime: str) -> str:
        return f"data:{mime};base64," + base64.b64encode(data).decode()

    def jpeg(data: bytes, quality: int) -> bytes:
        img = cv2.imdecode(np.frombuffer(data, np.uint8), cv2.IMREAD_COLOR)  # re-encoded smaller for the app bundle
        ok, buf = cv2.imencode(".jpg", img, [cv2.IMWRITE_JPEG_QUALITY, quality])
        assert ok
        return buf.tobytes()

    TEXTURES_TS.write_text(
        "// AUTO-GENERATED by services/api/scripts/make_demo_face.py. Do not edit by hand.\n"
        "export const DEMO_TEXTURES = {\n"
        f"  albedo: '{data_url(jpeg(result.albedo_jpg, 85), 'image/jpeg')}',\n"
        f"  smooth: '{data_url(jpeg(result.smooth_jpg, 82), 'image/jpeg')}',\n"
        f"  mask: '{data_url(result.mask_png, 'image/png')}',\n"
        f"  eyes: '{data_url(jpeg(result.eyes_jpg, 88), 'image/jpeg')}',\n"
        "};\n"
    )
    print(f"demo face written to {out / 'model.json'} and {TEXTURES_TS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
